import type {
  PanelPosition,
  PersistedState,
  ThinkingControlStyle,
  ViewMode,
} from "./ipc";
import type { PasteMarkerPaint, PasteMarkerStyle, PasteModeSetting } from "./paste-attach";
import type { TabLayout, TabRailSide } from "./tab-layout";

/**
 * Baseline default settings shipped with PiShift when cloned/downloaded fresh from GitHub.
 * Copies the exact user configuration while cleanly omitting all personal paths,
 * active tabs, recent folders, secrets, and credentials.
 */
export const DEFAULT_PERSISTED_SETTINGS: Omit<PersistedState, "tabs" | "activeIndex"> = {
  themeName: "Vesper",
  fontFamily: "",
  fontSize: 18,
  scrollSteps: 3,
  chatZoom: 1,
  defaultViewMode: "terminal" as ViewMode,
  toolDensity: "compact",
  collapseReasoningOnReply: false,
  rawTextOnExpand: false,
  autoUpdateOmpOnOpen: false,
  doneSoundEnabled: true,
  doneSoundVolume: 0.2,
  favoriteModels: ["gemini-3.7-flash", "claude-3-7-sonnet", "gpt-4o"],
  customModels: [
    {
      provider: "xai-oauth",
      id: "grok-4.6",
      name: "Grok 4.6",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/9o79qB.png",
    },
    {
      provider: "xai-oauth",
      id: "grok-4.20-0309-reasoning",
      name: "Grok 4.20R",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/9o79qB.png",
    },
    {
      provider: "xai-oauth",
      id: "grok-composer-2.5-fast",
      name: "Grok 2.5C",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/9o79qB.png",
    },
    {
      provider: "anthropic",
      id: "claude-opus-5",
      name: "Opus 5",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/H37rC3.png",
    },
    {
      provider: "anthropic",
      id: "claude-sonnet-5",
      name: "Sonnet 5",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/H37rC3.png",
    },
    {
      provider: "google-antigravity",
      id: "claude-sonnet-4-6",
      name: "Sonnet 4.6",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/H37rC3.png",
    },
    {
      provider: "google-antigravity",
      id: "gemini-3.8-flash",
      name: "3.8 Flash",
      iconUrl: "https://i.postimg.cc/bNSFXQLm/ahhhhhhh.png",
    },
    {
      provider: "openai-codex",
      id: "gpt-5.6-sol",
      name: "5.6 Sol",
      iconUrl: "https://chatgpt.com/favicon.ico",
    },
    {
      provider: "openai-codex",
      id: "gpt-5.6-terra",
      name: "5.6 Terra",
      iconUrl: "https://chatgpt.com/favicon.ico",
    },
    {
      provider: "openai-codex",
      id: "gpt-5.6-luna",
      name: "5.6 Luna",
      iconUrl: "https://chatgpt.com/favicon.ico",
    },
    {
      provider: "opencode-zen",
      id: "muse-spark-1.3-contributor-free",
      name: "Spark 1.3",
      iconUrl: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/DBsOQC.png",
    },
  ],
  showFavoritesOnly: false,
  showUsageInHeader: false,
  activityColors: {
    waiting: "#ff0059",
    thinking: "#c084fc",
    responding: "#f778d5",
    reading: "#38bdf8",
    editing: "#80ff00",
    running: "#4ade80",
    working: "#7aa2f7",
  },
  activityColorsOnTabs: true,
  todoPanelVisible: false,
  todoPanelMode: "overlay",
  hideTopButtonLabels: false,
  hideBottomButtonLabels: false,
  collapseTopBarToMenu: true,
  panelPosition: "top-right" as PanelPosition,
  tabPreviews: true,
  tabLayout: "vertical" as TabLayout,
  tabRailSide: "left" as TabRailSide,
  tabRailHoverReachPx: 24,
  thinkingControlStyle: "horizontal" as ThinkingControlStyle,
  usageTracker: {
    enabled: true,
    refreshIntervalMs: 60000,
    quotas: [
      {
        provider: "anthropic",
        label: "Claude 5 Hour",
        enabled: true,
        style: "bar",
      },
      {
        provider: "anthropic",
        label: "Claude 7 Day",
        enabled: false,
        style: "bar",
      },
      {
        provider: "openai-codex",
        label: "5 hours",
        enabled: true,
        style: "bar",
      },
      {
        provider: "google-antigravity",
        label: "Usage (OpenAI)",
        enabled: false,
        style: "bar",
      },
      {
        provider: "google-antigravity",
        label: "Usage (Anthropic)",
        enabled: false,
        style: "bar",
      },
      {
        provider: "google-antigravity",
        label: "Usage (Google)",
        enabled: true,
        style: "bar",
      },
      {
        provider: "xai-oauth",
        label: "SuperGrok Weekly Credits",
        enabled: true,
        style: "bar",
      },
      {
        provider: "openai-codex",
        label: "7 days",
        enabled: false,
        style: "bar",
      },
      {
        provider: "openai-codex",
        label: "7 days (gpt-reserve)",
        enabled: false,
        style: "bar",
      },
    ],
    providerIconUrls: {
      anthropic: "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/H37rC3.png",
      "openai-codex": "https://chatgpt.com/favicon.ico",
      "google-antigravity": "https://i.postimg.cc/bNSFXQLm/ahhhhhhh.png",
      "xai-oauth": "https://images.guns.lol/fb790494e15181d40c662760276c78639851a223/9o79qB.png",
    },
    iconPlacement: "beside",
    showPercent: true,
    orientation: "auto",
    combineAccounts: false,
  },
  settingsSectionCollapsed: {
    appearance: true,
    composer: true,
    "usage-tracker": false,
    "chat-view": false,
    interface: true,
    backup: true,
  },
  pasteMode: "ask" as PasteModeSetting,
  pasteMarkerStyle: "content" as PasteMarkerStyle,
  pasteMarkerPaint: "pill" as PasteMarkerPaint,
  pasteMarkerPulse: true,
};
